Get-Appxpackage *store* | Remove-Appxpackage
Get-Appxpackage *xbox* | Remove-Appxpackage 
Get-Appxpackage *alarm* | Remove-Appxpackage
Get-Appxpackage *people* | Remove-Appxpackage
Get-Appxpackage *maps* | Remove-Appxpackage
Get-Appxpackage *paint* | Remove-Appxpackage
Get-Appxpackage *photos* | Remove-Appxpackage
Get-Appxpackage *skype* | Remove-Appxpackage
Get-Appxpackage *phone* | Remove-Appxpackage
Get-Appxpackage *3d* | Remove-Appxpackage
Get-Appxpackage Microsoft.549981C3F5F10 | Remove-appxpackage
Get-Appxpackage *music* | Remove-Appxpackage
Get-Appxpackage *onedrive* | Remove-Appxpackage
Get-Appxpackage *help* | Remove-Appxpackage
Get-Appxpackage *snip* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Microsoft3DViewer* | Remove-Appxpackage
Get-Appxpackage *Microsoft.AppConnector* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingFinance* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingNews* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingSports* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingTranslator* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingWeather* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingFoodAndDrink* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingHealthAndFitness* | Remove-Appxpackage
Get-Appxpackage *Microsoft.BingTravel* | Remove-Appxpackage
Get-Appxpackage *Microsoft.MinecraftUWP* | Remove-Appxpackage
Get-Appxpackage *Microsoft.GamingServices* | Remove-Appxpackage
Get-Appxpackage *Microsoft.GetHelp* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Getstarted* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Messaging* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Microsoft3DViewer* | Remove-Appxpackage
Get-Appxpackage *Microsoft.MicrosoftSolitaireCollection* | Remove-Appxpackage
Get-Appxpackage *Microsoft.NetworkSpeedTest* | Remove-Appxpackage
Get-Appxpackage *Microsoft.News* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Office.Lens* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Office.Sway* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Office.OneNote* | Remove-Appxpackage
Get-Appxpackage *Microsoft.OneConnect* | Remove-Appxpackage
Get-Appxpackage *Microsoft.People* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Print3D* | Remove-Appxpackage
Get-Appxpackage *Microsoft.SkypeApp* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Wallet* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Whiteboard* | Remove-Appxpackage
Get-Appxpackage *Microsoft.WindowsAlarms* | Remove-Appxpackage
Get-Appxpackage *microsoft.windowscommunicationsapps* | Remove-Appxpackage
Get-Appxpackage *Microsoft.WindowsFeedbackHub* | Remove-Appxpackage
Get-Appxpackage *Microsoft.WindowsMaps* | Remove-Appxpackage
Get-Appxpackage *Microsoft.WindowsPhone* | Remove-Appxpackage
Get-Appxpackage *Microsoft.WindowsSoundRecorder* | Remove-Appxpackage
Get-Appxpackage *Microsoft.XboxApp* | Remove-Appxpackage
Get-Appxpackage *Microsoft.ConnectivityStore* | Remove-Appxpackage
Get-Appxpackage *Microsoft.CommsPhone* | Remove-Appxpackage
Get-Appxpackage *Microsoft.ScreenSketch* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Xbox.TCUI* | Remove-Appxpackage
Get-Appxpackage *Microsoft.XboxGameOverlay* | Remove-Appxpackage
Get-Appxpackage *Microsoft.XboxGameCallableUI* | Remove-Appxpackage
Get-Appxpackage *Microsoft.XboxSpeechToTextOverlay* | Remove-Appxpackage
Get-Appxpackage *Microsoft.MixedReality.Portal* | Remove-Appxpackage
Get-Appxpackage *Microsoft.XboxIdentityProvider* | Remove-Appxpackage
Get-Appxpackage *Microsoft.ZuneMusic* | Remove-Appxpackage
Get-Appxpackage *Microsoft.ZuneVideo* | Remove-Appxpackage
Get-Appxpackage *Microsoft.Getstarted* | Remove-Appxpackage
Get-Appxpackage *Microsoft.MicrosoftOfficeHub* | Remove-Appxpackage
Get-Appxpackage **EclipseManager** | Remove-Appxpackage
Get-Appxpackage **ActiproSoftwareLLC** | Remove-Appxpackage
Get-Appxpackage **AdobeSystemsIncorporated.AdobePhotoshopExpress** | Remove-Appxpackage
Get-Appxpackage **Duolingo-LearnLanguagesforFree** | Remove-Appxpackage
Get-Appxpackage **PandoraMediaInc** | Remove-Appxpackage
Get-Appxpackage **CandyCrush** | Remove-Appxpackage
Get-Appxpackage **BubbleWitch3Saga** | Remove-Appxpackage
Get-Appxpackage **Wunderlist** | Remove-Appxpackage
Get-Appxpackage **Flipboard** | Remove-Appxpackage
Get-Appxpackage **Twitter** | Remove-Appxpackage
Get-Appxpackage **Facebook** | Remove-Appxpackage
Get-Appxpackage **Royal Revolt** | Remove-Appxpackage
Get-Appxpackage **Sway** | Remove-Appxpackage
Get-Appxpackage **Speed Test** | Remove-Appxpackage
Get-Appxpackage **Dolby** | Remove-Appxpackage
Get-Appxpackage **Viber** | Remove-Appxpackage
Get-Appxpackage **ACGMediaPlayer** | Remove-Appxpackage
Get-Appxpackage **Netflix** | Remove-Appxpackage
Get-Appxpackage **OneCalendar** | Remove-Appxpackage
Get-Appxpackage **LinkedInforWindows** | Remove-Appxpackage
Get-Appxpackage **HiddenCityMysteryofShadows** | Remove-Appxpackage
Get-Appxpackage **Hulu** | Remove-Appxpackage
Get-Appxpackage **HiddenCity** | Remove-Appxpackage
Get-Appxpackage **AdobePhotoshopExpress** | Remove-Appxpackage
Get-Appxpackage **HotspotShieldFreeVPN** | Remove-Appxpackage
Get-Appxpackage **Microsoft.Advertising.Xaml* | Remove-Appxpackage